name: flutter_template
description: A Very Good Project created by Very Good CLI.
version: 2.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  auto_route: ^2.4.0
  core:
    path: packages/core
  dartz: ^0.10.0
  equatable: ^2.0.3
  errors:
    path: packages/errors
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_riverpod: 1.0.0-dev.7
  flutter_vector_icons: ^1.0.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  freezed_annotation: ^0.14.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.0
  intl: ^0.17.0
  oxidized: ^5.1.0
  period_repository:
    path: packages/period_repository
  salomon_bottom_bar: ^3.1.0
  token_service:
    path: packages/token_service

dev_dependencies:
  auto_route_generator: ^2.4.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
  - family: UnmdpIcon
    fonts:
      - asset: assets/fonts/UnmdpIcon.ttf