name: token_service
description: Dart package which manages the token.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  core:
    path: ../core
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^2.3.0
