name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  core:
    path: ../core
  errors:
    path: ../errors
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.3
  google_sign_in: ^5.1.0
  json_annotation: ^4.1.0
  json_serializable: ^5.0.2
  meta: ^1.7.0
  oxidized: ^5.1.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  # mocktail: ^0.1.4
  mocktail: null
  very_good_analysis: ^2.3.0
