name: form_inputs
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  core:
    path: ../core
  errors:
    path: ../errors

  formz: ^0.4.0
  intl: ^0.17.0

dev_dependencies:
  very_good_analysis: ^2.3.0
