name: errors
description: Dart package which manages app common errors.
version: 1.0.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.14.3
  oxidized: ^5.1.0

dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^0.14.5
  test: null
  very_good_analysis: ^2.3.0
