/// Flutter icons UnmdpIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UnmdpIcon
///      fonts:
///       - asset: fonts/UnmdpIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class UnmdpIcon {
  UnmdpIcon._();

  static const _kFontFam = 'UnmdpIcon';

  static const IconData ola = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
}
